version: '3'

services:

  mysql:
    image: "mysql"
    restart: always
    network_mode: host
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev6914
    volumes:
      - "${CONTAINERS_DATA_DIR}/mysql:/var/lib/mysql"